@startuml
title 透過 AWS IoT + WiFiModule2 傳送指令給 Sesame5
participant 手機app
participant Sesame5
participant WiFiModule2

box "AWS IoT" #White/ffcc7c
participant "WiFiModule2 Shadow"
participant "Sesame5 Shadow"
end box

note over WiFiModule2, Sesame5: \
已建立BLE連線,並已完成BLE_login且已建立AESCCM加密通道

手機app -> "WiFiModule2 Shadow": (command, key_idx, 手機app_publicKey, timestamp, SIG)
"WiFiModule2 Shadow" -> WiFiModule2: (command, key_idx, 手機app_publicKey, timestamp, SIG)
WiFiModule2 -> Sesame5: (command, key_idx, 手機app_publicKey, timestamp, SIG)

note over Sesame5, 手機app: \
SIG=AESCMAC(user_key, command+  key_idx+手機app_publicKey+timestamp  +ECDH_sharedSecret)\n\
ECDH_sharedSecret = ECDH(Sesame5_keypairs, 手機app_keypairs)

Sesame5 -> Sesame5: 開鎖
Sesame5 -> WiFiModule2: Sesame狀態\n(是否鎖上?、電池、角度)
WiFiModule2 -> "Sesame5 Shadow": 同步 Sesame狀態\n(是否鎖上?、電池、角度)
"Sesame5 Shadow" -> 手機app: 同步 Sesame狀態\n(是否鎖上?、電池、角度)

@enduml
