@startuml

|Sesame(APP)|
start 
:noBleSignal;
:receivedBle;
:bleConnecting;
:waitingGatt;

|Sesame5|
if(isRegistered?) then (No!)
  :readyToRegister;
  :registering;
  
  |Sesame(APP)|
  :locked;
  :unlocked;
  stop
else (Yes!)
  |Sesame5|
  :bleLogining;
	
	if(isLogin?) then (No!)
	:bleDisconnecting;
  |Sesame(APP)|

	:noBleSignal;
stop
	else (Yes!)
	|Sesame5|
	  :moved;
		:ready;

  stop
endif

@enduml