@startuml
participant BLEcentral [
    iOS/Android/ESP32
    ----
    BLE Central app
]
participant Server [
    =Sesame
    ----
    BLE Peripheral
]

BLEcentral -> Server: **Request**\n<&bluetooth>(基於 BLE Write without response 實作)
Server --> BLEcentral: **Response**\n<&bluetooth>(基於 BLE Notify 實作)
Server -> Server: Process
Server --> BLEcentral: **Publish**\n<&bluetooth>(基於 BLE Notify 實作)

@enduml